export const products = [
  {
    id: 1,
    name: 'Wireless Headphones',
    price: 59.99,
    description: 'High-quality wireless headphones with noise cancellation.',
    image: 'https://via.placeholder.com/400x300?text=Headphones',
    category: 'electronics', 
  },
  {
    id: 2,
    name: 'Smartwatch',
    price: 129.99,
    description: 'A stylish smartwatch with multiple health tracking features.',
    image: 'https://via.placeholder.com/400x300?text=Smartwatch',
    category: 'electronics', 
  },
  {
    id: 3,
    name: 'Gaming Mouse',
    price: 39.99,
    description: 'Ergonomic gaming mouse with customizable buttons.',
    image: 'https://via.placeholder.com/400x300?text=Gaming+Mouse',
    category: 'electronics', 
  },
  {
    id: 4,
    name: 'Bluetooth Speaker',
    price: 89.99,
    description: 'Portable Bluetooth speaker with powerful sound.',
    image: 'https://via.placeholder.com/400x300?text=Speaker',
    category: 'electronics', 
  },
  {
    id: 5,
    name: 'Tablet',
    price: 249.99,
    description: 'High-resolution tablet for work and entertainment.',
    image: 'https://via.placeholder.com/400x300?text=Tablet',
    category: 'electronics', 
  },
  {
    id: 6,
    name: 'Running Shoes',
    price: 79.99,
    description: 'Comfortable running shoes for all terrains.',
    image: 'https://via.placeholder.com/400x300?text=Running+Shoes',
    category: 'fashion', 
  },
  {
    id: 7,
    name: 'Casual T-Shirt',
    price: 19.99,
    description: 'Stylish casual t-shirt for daily wear.',
    image: 'https://via.placeholder.com/400x300?text=T-Shirt',
    category: 'fashion', 
  },
  {
    id: 8,
    name: 'Living Room Sofa',
    price: 499.99,
    description: 'Spacious and comfortable living room sofa.',
    image: 'https://via.placeholder.com/400x300?text=Sofa',
    category: 'home & living', 
  },
  {
    id: 9,
    name: 'Wall Clock',
    price: 39.99,
    description: 'Elegant wall clock for your home.',
    image: 'https://via.placeholder.com/400x300?text=Clock',
    category: 'home & living', 
  },
  {
    id: 10,
    name: 'Dumbbells Set',
    price: 59.99,
    description: 'Set of dumbbells for strength training.',
    image: 'https://via.placeholder.com/400x300?text=Dumbbells',
    category: 'sports', 
  },
];
